image: ubuntu:focal

variables:
  TELEGRAM_MESSAGE: CI - CD STATUS
  IMAGE_NAME: sulaymonyahyo/portfolio
  DEV_PORT: 6236

stages:
  - build_dev
  - deploy_dev

cache:
  paths:
    - .yarn
    - node_modules
    - build
    - message.txt

build_dev:
  stage: build_dev
  image: docker:20.10.16
  services:
    - docker:20.10.16-dind
  variables:
    DOCKER_TLS_CERTDIR: "/certs"
  before_script:
    - docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
  script:
    - docker build -t $IMAGE_NAME:$(cat package.json | grep '"version"' | cut -d '"' -f 4) .
    - docker push $IMAGE_NAME:$(cat package.json | grep '"version"' | cut -d '"' -f 4)

deploy_dev:
  stage: deploy_dev
  before_script:
    - which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )
    - chmod 600 $SSH_KEY
  script:
    - ssh -o StrictHostKeyChecking=no -p $SSH_PORT -i $SSH_KEY $USER@$HOST "
      docker login -u $DOCKER_USER -p $DOCKER_PASSWORD &&
      docker ps -aq | xargs docker stop | xargs docker rm &&
      docker run -d -p $DEV_PORT:80 -p 443:443 $IMAGE_NAME:$(cat package.json | grep '"version"' | cut -d '"' -f 4)"
  needs:
    - build_dev
