image: ubuntu:focal

variables:
  IMAGE_NAME: registry.gitlab.com/sulaymonyahyo/holy-quran-server
  DEV_PORT: 6236

stages:
  - variables
  - build
  - test
  - deploy & release

run-test-variables:
  stage: variables
  image: maven:3.8.3-openjdk-17
  script:
    - echo "BUILD_VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)" >> build.env
  artifacts:
    reports:
      dotenv: build.env

build-image:
  stage: build
  image: docker:20.10.16
  services:
    - docker:20.10.16-dind
  before_script:
    - docker login -u $DOCKER_USER -p $DOCKER_PASSWORD registry.gitlab.com
  script:
    - docker build -f docker/dev/Dockerfile --cache-from $IMAGE_NAME:latest --tag $IMAGE_NAME:$BUILD_VERSION --tag $IMAGE_NAME:latest .
    - docker push $CI_REGISTRY_IMAGE:$BUILD_VERSION
    - docker push $CI_REGISTRY_IMAGE:latest
  needs:
    - run-test-variables

run-image-local:
  stage: test
  image: docker:20.10.16
  services:
    - docker:20.10.16-dind
  script:
    - docker run $IMAGE_NAME:$BUILD_VERSION
  needs:
    - build-image
  timeout: 2m

deploy-aws:
  stage: deploy & release
  before_script:
    - which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )
    - chmod 600 $SSH_KEY
  script:
    - ssh -o StrictHostKeyChecking=no -p $SSH_PORT -i $SSH_KEY $SSH_USER@$HOST "
      docker login -u $DOCKER_USER -p '$DOCKER_PASSWORD' registry.gitlab.com &&
      docker ps -aq | xargs docker stop | xargs docker rm &&
      docker run -d -p $DEV_PORT:6236 $IMAGE_NAME:$BUILD_VERSION"
  needs:
    - run-image-local
  timeout: 5m

release_job:
  stage: deploy & release
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  rules:
    - if: $CI_COMMIT_TAG                 # Run this job when a tag is created
  script:
    - echo "running release_job for $TAG"
  release:                               # See https://docs.gitlab.com/ee/ci/yaml/#release for available properties
    name: 'Release $BUILD_VERSION'
    tag_name: '$CI_COMMIT_TAG'
    description: '$CI_COMMIT_TAG'
    ref: '$CI_COMMIT_SHA'
  needs:
    - run-image-local
  timeout: 5m
