image: ubuntu:focal

variables:
  IMAGE_NAME: registry.gitlab.com/sulaymonyahyo/holy-quran-server
  DEV_PORT: 6236

stages:
  - variables
  - build
  - deploy & release

run-test-variables:
  stage: variables
  image: maven:3.8.3-openjdk-17
  script:
    - echo "BUILD_VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)" >> build.env
  artifacts:
    reports:
      dotenv: build.env

build-image:
  stage: build
  image: docker:20.10.16
  services:
    - docker:20.10.16-dind
  variables:
    DOCKER_TLS_CERTDIR: "/certs"
  before_script:
    - docker login registry.gitlab.com -u $DOCKER_USER -p '$DOCKER_PASSWORD'
  script:
    - docker build -f docker/dev/Dockerfile -t $IMAGE_NAME:$BUILD_VERSION .
    - docker push $IMAGE_NAME:$BUILD_VERSION
  needs:
    - run-test-variables

deploy-aws:
  stage: deploy & release
  before_script:
    - which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )
    - chmod 600 $SSH_KEY
  script:
    - ssh -o StrictHostKeyChecking=no -p $SSH_PORT -i $SSH_KEY $SSH_USER@$HOST "
      docker login -u $DOCKER_USER -p '$DOCKER_PASSWORD' &&
      docker ps -aq | xargs docker stop | xargs docker rm &&
      docker run -d -p $DEV_PORT:6236 $IMAGE_NAME:$BUILD_VERSION"
  needs:
    - build-image
  timeout: 10m

release_job:
  stage: deploy & release
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  rules:
    - if: $CI_COMMIT_TAG                 # Run this job when a tag is created
  script:
    - echo "running release_job for $TAG"
  release:                               # See https://docs.gitlab.com/ee/ci/yaml/#release for available properties
    name: 'Release $BUILD_VERSION'
    tag_name: '$CI_COMMIT_TAG'
    description: '$CI_COMMIT_TAG'
    ref: '$CI_COMMIT_SHA'
  needs:
    - build-image
