version: '3.8'

services:
  backend:
    container_name: quran-server
    image: sulaymonyahyo/quran-server:${CI_COMMIT_TAG}
    build:
      dockerfile: docker/dev/Dockerfile
    ports:
      - "6236:6236"
    environment:
      - DATABASE_URL=jdbc:postgresql://db:5432/ihb
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=admin
    depends_on:
      - db

  db:
    container_name: postgesql
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: ihb
    ports:
      - "5432:5432"
